server:
    port: 8081
auth:
    token:
        issuer:
            urls:
                google: http://home-auth-service:8081/home/auth/google/validate/id-token
                home-stack-auth: http://home-auth-service:8081/home/auth/home/token/validate
flyway:
    baselineOnMigrate: true
    enabled: false
    locations: ~/test
opentracing:
    jaeger:
        log-spans: true
        udp-sender:
            host: jaeger-agent
            port: 6831
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            connection-timeout: 30000
            idle-timeout: 600000
            max-lifetime: 1800000
            maximum-pool-size: 10
            minimum-idle: 10
        password: password
        url: jdbc:mysql://mysql:3306/home-stack
        username: root
    debug: true
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
                id:
                    new_generator_mappings: true
        show-sql: false
iot:
    mqtt:
        enable: true
        host: arktr4szflm0y-ats.iot.ap-south-1.amazonaws.com
        port: 8883
    secure:
        keystore-file: /home/alok/keystore.jks
        keystore-file-path-type: ABSOLUTE
        truststore-file: /home/alok/trustore.jks
        truststore-file-path-type: ABSOLUTE